package code.model;

public class T {
   public static String trangbi1;
   public static String trangbi2;
   public static String choan;
   public static String chuadunguyenlieu;
   public static String bandabo;
   public static String bophiphongvao;
   public static String khongthechuyenhoa;
   public static String chuyenhoa;
   public static String mTips;
   public static String khongthetao;
   public static String tao;
   public static String kcobang;
   public static String banghoi;
   public static String moivaobang;
   public static String nangcap;
   public static String khongthebothem;
   public static String layra;
   public static String quatang;
   public static String tchangsize;
   public static String bigScreen;
   public static String smallScreen;
   public static String textXacThuc;
   public static String touch;
   public static String bannhieu;
   public static String xincho;
   public static String tDie;
   public static String hoisinhtaicho;
   public static String hoisinhsau;
   public static String tgetPass;
   public static String txacthuc;
   public static String khongcotinnhan;
   public static String khongconhom;
   public static String xacthuc;
   public static String matkhau;
   public static String taikhoan;
   public static String mvut;
   public static String ban;
   public static String vut;
   public static String sudung;
   public static String doi;
   public static String chatcongcong;
   public static String text12;
   public static String tinhanh;
   public static String thulinh;
   public static String haydengap;
   public static String kinang;
   public static String vao;
   public static String point;
   public static String hoicong;
   public static String chat;
   public static String yes;
   public static String thaoco;
   public static String khongtheketnoi;
   public static String khongthenhan;
   public static String map;
   public static String cuonghoa;
   public static String bovao;
   public static String tile;
   public static String connectFail;
   public static String loimoiThachdau;
   public static String Free;
   public static String Mua_Bang_Ngoc;
   public static String Mua_bang_vang;
   public static String hoiKTG;
   public static String chatWorld;
   public static String login;
   public static String kill;
   public static String hoihoisinh;
   public static String hoivelang;
   public static String hoisinh;
   public static String nhom1;
   public static String khong;
   public static String dongy;
   public static String hoivaonhom;
   public static String moivaonhom;
   public static String arena;
   public static String clear;
   public static String deokhan;
   public static String hopthu;
   public static String bat;
   public static String dosat;
   public static String beginChat;
   public static String nhom;
   public static String bang;
   public static String Toc_khac;
   public static String hoatdong;
   public static String quayvelang;
   public static String wait;
   public static String velang;
   public static String tinden;
   public static String khongthecong;
   public static String nhapso;
   public static String fullInven;
   public static String khongdump;
   public static String chatngoc;
   public static String chatkenhTG;
   public static String kenhTG;
   public static String sell;
   public static String doyouwant;
   public static String hoanthanhnhiemvu;
   public static String danhannhiemvu;
   public static String nhannhiemvu;
   public static String nhan;
   public static String bietthemthongtin;
   public static String dengapnpc;
   public static String noidung;
   public static String phanthuong;
   public static String muctieu;
   public static String gia;
   public static String gia_ban_lai;
   public static String nhat;
   public static String giet;
   public static String luong;
   public static String xu;
   public static String no;
   public static String doyouwantbuy;
   public static String withprice;
   public static String nhapsoluong;
   public static String Buy;
   public static String hanhtrang;
   public static String OK;
   public static String dangxuat;
   public static String trochuyen;
   public static String dongtap;
   public static String dongtrochyen;
   public static String tuychon;
   public static String close;
   public static String diem;
   public static String conectfail;
   public static String back;
   public static String namehungcanh;
   public static String boqua;
   public static String next;
   public static String phai;
   public static String monphai;
   public static String nam;
   public static String nu;
   public static String nhanvat;
   public static String congDiem;
   public static String Gangphim;
   public static String phimso;
   public static String chuahoc;
   public static String chuamo;
   public static String di;
   public static String haha;
   public static String hoanthanh;
   public static String tennhanvat;
   public static String thongtin;
   public static String donggianhang;
   public static String huygianhang;
   public static String choimoi;
   public static String cotaikhoan;
   public static String server;
   public static String choitiep;
   public static String taikhoankhac;
   public static String thaydo;
   public static String naptien;
   public static String changpk;
   public static String xuongngua;
   public static String auto;
   public static String nhiemvu;
   public static String thoat;
   public static String diendan;
   public static String amthanh;
   public static String Sudung;
   public static String Vut;
   public static String Ban;
   public static String type;
   public static String Thoigianhoi;
   public static String Thoigianhotro;
   public static String LvYeuCau;
   public static String Tieuhaonoiluc;
   public static String Banbe;
   public static String Tuyetgiao;
   public static String Xemthongtin;
   public static String chapnhan;
   public static String tuchoi;
   public static String yeucauketban;
   public static String hoigiaodich;
   public static String hoithachdau;
   public static String huygiaodich;
   public static String loimoiParty;
   public static String moivaoclan;
   public static String tabThuLinh;
   public static String tabBangHoi;
   public static String cancel;
   public static String info;
   public static String delMess;
   public static String view;
   public static String menu;
   public static String mevent;
   public static String noEvent;
   public static String coin;
   public static String loimoikb;
   public static String npcCharTalk;
   public static String giaotiep;
   public static String level;
   public static String somuctieu;
   public static String napgoogle;
   public static String[][] Texintro;
   public static String[][] talkwhenfight;
   public static String[][] infoclass;
   public static String[][] classintro;
   public static String[][] menuAuto;
   public static String[] hungcanh;
   public static String[] className;
   public static String dongdoi = "";
   public static String[] namelistQuest;
   public static String[] nameTabAuto;
   public static String[] typeSkill;
   public static String[] tfocus;
   public static String[] petinfo;
   public static String[] infoTiemNang;
   public static String[] Tabmuctieu;
   public static String[] listKhan;
   public static String[] serverName;
   public static String[] nametiemnang;
   public static String[] tClan;
   public static String[] infoClan;
   public static String[] Tips;
   public static String chon;
   public static String tinnpc;
   public static String taidata;

   public T() {
      taidata = "Đang tải dữ liệu";
      tinnpc = "Npc";
      chon = "Chọn";
      trangbi1 = "T.Bị 1";
      trangbi2 = "T.Bị 2";
      choan = "Cho ăn";
      chuadunguyenlieu = "Bạn chưa bỏ đủ nguyên liệu";
      bandabo = "Bạn đã bỏ vật phẩm loại này vào rồi";
      bophiphongvao = "Ngươi hãy bỏ phi phong vào ta sẽ nâng cấp cho";
      khongthechuyenhoa = "Không thể chuyển hóa";
      chuyenhoa = "Chuyển hóa";
      mTips = "Tips: ";
      khongthetao = "Không thể tạo";
      tao = "Tạo";
      kcobang = "Chức năng chỉ dành cho người đã tham gia bang hội";
      banghoi = "Bang hội";
      moivaobang = "Mời vào bang";
      nangcap = "Nâng cấp";
      khongthebothem = "Không thể bỏ thêm";
      layra = "Lấy ra";
      Mua_Bang_Ngoc = "Mua lượng";
      Mua_bang_vang = "Mua xu";
      Free = "Miễn phí";
      quatang = "Quà tặng";
      tchangsize = "Bạn vừa chuyển qua kích thước màn hình khác. Bạn có muốn chạy lại game để có tác dụng không?";
      bigScreen = "Màn hình to";
      smallScreen = "Màn hình nhỏ";
      textXacThuc = " của bạn chưa được xác thực tài khoản, nếu đăng nhập tài khoản khác, nhân vật của bạn sẽ mất vĩnh viễn";
      touch = "Touch/keypad";
      bannhieu = "Bán nhiều";
      xincho = "xin chờ...";
      tDie = "Chết rồi";
      hoisinhtaicho = "Hồi sinh tại chỗ 2 lượng";
      hoisinhsau = "Hồi sinh sau: ";
      tgetPass = "Bạn có muốn lấy lại (hoặc đổi) mật khẩu ?";
      txacthuc = "Nhân vật của bạn chưa được xác thực tài khoản, nếu đăng nhập tài khoản khác, nhân vật của bạn sẽ mất vĩnh viễn";
      khongcotinnhan = "Hiện tại không có tin nhắn";
      khongconhom = "Hiện tại bạn không có nhóm";
      taikhoan = "Tài Khoản";
      matkhau = "Mật Khẩu";
      mvut = "Khác";
      ban = "Bán";
      vut = "Khác";
      gia_ban_lai = "Giá bán lại: ";
      sudung = "Sử dụng";
      somuctieu = "Mục tiêu";
      doi = "Đổi";
      chatcongcong = "Chat công cộng";
      text12 = "12+ Chơi quá 180 phút mỗi ngày sẽ hại sức khỏe.";
      tinhanh = "Tinh Anh";
      thulinh = "Thủ Lĩnh";
      haydengap = "Hãy đến gặp ";
      kinang = "kĩ năng ";
      vao = "vào ";
      point = "điểm";
      hoicong = "Bạn có muốn cộng ";
      chat = "Trò chuyện";
      yes = "Có";
      thaoco = "Tháo cờ";
      khongtheketnoi = "Không thể kết nối đến máy chủ";
      level = "Cấp độ";
      giaotiep = "Giao tiếp";
      npcCharTalk = "Ta có thể giúp gì cho ngươi";
      khongthenhan = "Bạn chưa thể nhận nhiệm vụ này";
      map = "Bản Đồ";
      cuonghoa = "Cường Hóa";
      bovao = "Bỏ vào";
      tile = "Tỉ lệ";
      connectFail = "Bạn bị mất kết nối với máy chủ.";
      loimoiThachdau = "lời mời thách đấu";
      hoiKTG = "Chat kênh thế giới với giá 5 lượng";
      chatWorld = "Kênh TG";
      login = "Đăng nhập";
      kill = "Giết: ";
      hoihoisinh = "Bạn có muốn hồi sinh tại chỗ không ?";
      hoivelang = "Bạn có muốn về làng không ?";
      hoisinh = "Hồi sinh";
      nhom1 = "Nhóm";
      khong = "không";
      dongy = "Đồng ý";
      hoivaonhom = "Bạn có muốn vào nhóm với ";
      moivaonhom = " mời bạn vào nhóm";
      arena = "Khu ";
      clear = "Xóa";
      deokhan = "Đeo cờ";
      hopthu = "Hộp thư";
      bat = "Bật";
      dosat = "Bạn có muốn bật chế độ đồ sát?";
      beginChat = "Trò chuyện với ";
      bang = "cla";
      nhom = "pty";
      quayvelang = "Quay về làng";
      velang = "Về làng";
      wait = "Chờ";
      tinden = "Tin Đến";
      khongthecong = "Không thể cộng";
      nhapso = "Nhập số";
      fullInven = "Hành trang đầy";
      khongdump = "Không đủ MP";
      chatngoc = "Bạn có muốn chát kênh thế giới với giá 5 lượng ?";
      chatkenhTG = "Kênh Thế Giới";
      kenhTG = "Kênh.TG";
      sell = "bán";
      doyouwant = "Bạn có muốn ";
      hoanthanhnhiemvu = "Chúc mừng bạn đã hoàn thành nhiệm vụ ";
      danhannhiemvu = "Đã nhận nhiệm vụ ";
      nhannhiemvu = "Nhận nhiệm vụ ";
      nhan = "Nhận";
      dengapnpc = "Hãy đến gặp ";
      bietthemthongtin = " để biết thêm thông tin.";
      noidung = "Nội Dung: ";
      phanthuong = "Phần Thưởng: ";
      muctieu = "Mục Tiêu: ";
      gia = "Giá: ";
      nhat = "Nhặt ";
      giet = "Diệt ";
      luong = "Lượng";
      xu = "Bạc";
      no = "Không";
      doyouwantbuy = "Bạn có muốn mua";
      withprice = "với giá";
      nhapsoluong = "Nhập số lượng";
      Buy = "Mua";
      hanhtrang = "Hành Trang";
      OK = "OK";
      dangxuat = "Đăng Xuất";
      trochuyen = "Trò chuyện";
      dongtap = "Đóng tab này";
      dongtrochyen = "Đóng trò chuyện";
      tuychon = "Chọn";
      close = "Đóng";
      amthanh = "Âm Thanh";
      diendan = "Diễn Đàn";
      thoat = "Thoát";
      nhiemvu = "Nhiệm Vụ";
      auto = "Tự động";
      xuongngua = "Xuống Ngựa";
      changpk = "Đồ Sát";
      naptien = "Nạp Tiền";
      thaydo = "Thay Đồ";
      diem = "Điểm: ";
      conectfail = "Kết nối thất bại, vui lòng kiểm tra lại đường truyền.";
      back = "Quay Lại";
      namehungcanh = "Hung Canh";
      boqua = "Bỏ Qua Giới Thiệu";
      dongdoi = "đồng đội";
      next = "Tiếp";
      phai = "Phái";
      monphai = "Môn phái có thể gia nhập khi đạt cấp độ 10 :";
      nam = "Nam";
      nu = "Nữ";
      nhanvat = "Nhân vật";
      thongtin = "Tạo Nhân Vật";
      congDiem = "Cộng";
      Gangphim = "Gán Phím";
      phimso = "Phím ";
      chuahoc = "Chưa học kỹ năng này";
      chuamo = "Kỹ năng này đang bị khoá";
      di = "Đi";
      hoanthanh = "Hoàn Thành";
      tennhanvat = "Tên Nhân Vật";
      choimoi = "Chơi Mới";
      cotaikhoan = "Có Tài Khoản";
      server = "Máy Chủ: ";
      choitiep = "Chơi Tiếp: ";
      taikhoankhac = "Tài Khoản Khác";
      donggianhang = "Đóng gian hang";
      huygianhang = "Hủy gian hàng";
      napgoogle = "Mệnh giá";
      petinfo = new String[]{"Kinh nghiệm: ", "Sức khỏe: ", "Sơ cấp: ", "Kỹ năng: "};
      Tips = new String[]{"Train cùng nhau không cần party sẽ được nhiều xp hơn", "Thời gian thi đấu lôi đài diễn ra từ 21h đến 22h hằng ngày ", "TỈ lệ rớt đồ trong vượt ải cao hơn bên ngoài", "Lệnh bài gia tốc khi sử dụng sẽ làm 1 nhiệm vụ nhận exp", "Cường hóa 10 món 5 sao sẽ có hiệu ứng màu xanh", "Cường hóa 10 món 8 sao sẽ có hiệu ứng màu cam", "Cường hóa 5 món 6 sao sẽ có hiệu ứng màu đỏ", "Cường hóa 5 món 6.5 sao sẽ có hiệu ứng màu tím", "Hãy thử vận may tại NPC Tiểu Liên với nhiều phần quà hấp dẫn từ xu , exp, trang bị, đá cường hóa, bùa bảo hộ .....", "Bạn có thể nạp tiền tại NPC Tiền Thiên Phú tại Tuyết Sơn Trấn, thanh menu hoặc trên diển đàn game ", "Người chơi sẽ nhận được quà nếu các bạn chơi game đủ số phút", "Trang bị vàng trở lên mới được cường hóa", "Những mốc quy định 2.5 sao và 5 sao sẽ không bị tụt cấp khi cường hóa thất bại", "Hảy tham gia vào diển đàn game để trao đổi thông tin và thủ thuật chơi game tại: 5ltb.com", "Giết 1 người sẽ bị 100 điểm PK", "Nếu số điểm PK lớn hơn hoặc bằng 2.000 sẽ bị đưa vào Ốc Đảo", "Khi đạt lv 50,  bạn hãy tập hợp những anh hùng lại bằng cách lập bang", "Nâng cấp đồ tại NPC Lực Uy", "Giới hạn level khi săn boss là +-5 level so với level boss", "Săn boss hằng ngày để nhận trang bị và item hiếm", "Đăng ký và tham gia lôi đài ở NPC chưởng môn", "Cấp độ 20 sẽ mở giao dịch cá nhân", "Cấp độ để vào khu mua bán là level 10 trở lên", "Thay vì mua hp mp hồi theo số lượng, bạn có thể mua thức ăn hồi theo thời gian", "Cấp độ 40 sẽ mở PK", "Cấp độ 30 sẽ mở vượt ải", "Tối đa vật phẩm như mp,hp,đá cường hóa,... là là 32.000 trong hành trang", "Bật đồ sát sẽ được tăng 5% dam , nếu ở trạng thái đồ tể thì sẽ là 10%", "Khi đánh đủ 10 quái hay 100 quái hay 1.000 quái , 10.000 quái các bạn đều được tặng lượng", "Mỗi ngày có thể làm tối đa 20 lần nhiệm vụ hằng ngày", "Thách đấu thắng 10 người khác nhau trên level của bản thân sẽ được tặng x3 exp", "Vượt ải nhóm yêu cầu từ 3 -5 người", "Cường hóa trang bị tối đa là 8 sao", "Một ngày có thể làm tối đã là 20 nhiệm vụ hằng ngày", "Tóc miễn phí sẽ có ở NPC Bạch Mi , các bạn chỉ cần vào NPC Bạch Mi thay tóc mình muốn", "Bạn muốn đẹp trai và xinh gái? Hãy đến các NPC:Ma Lạc Tuyết , Dư Y , Trầm Nhược Băng , Giới Định Thượng Nhân , Thạch Hồng để cắt ngay", "x2 bang hội chỉ có thể mua được khi bạn vào bang nhé", "Nếu đang có mang tóc lượng mà đổi sang tóc miễn phí ở Bạch Mi xem như là mất tóc lượng , khi mua lại sẽ vẫn mất lượng", "Phí giao dịch cá nhân và ở khu mua bán là 10%", "Boss xuất hiện ở những khu 0/200", "Thời gian tái sinh boss hằng ngày tính từ thời điểm chết là 8h", "Item tẩy luyên đan dùng để tẩy tiềm năng nhân vật", "Item Hồi nguyên đơn dùng để tẩy kỹ năng nhân vật", "Bùa bảo hộ giúp trang bị không bị rớt sao khi cường hóa thất bại", "Bùa may mắn giúp tăng tỉ lệ cường hóa thành công", "Số lượng đá khi cường hóa bỏ vào tối đa là 10 viên", "Cường hóa trang bị bằng lượng có tỉ lệ thành công cao hơn bằng xu", "Sách kỹ năng level 40 có thể kiếm thông qua mở rương và săn boss hằng ngày", "Sách kỹ năng level 50 có thể kiếm thông qua săn boss hằng ngày", "Level để gia nhập bang là 40", "Trong thời gian diễn ra lôi đài bạn có thể xem những trận đấu  ở làng an bình trấn - Bia Ghi Nhớ", "Cấp độ để gia nhập môn phái là 10", "Cho tiền Lão Ăn Mày để được những phần quà hấp dẫn", "Phí mở rộng kho đồ là 200 lượng đối với 20 ô", "Khi con ma xuất hiện bạn phải giết thủ công hoặc tự động giết ma nếu có bùa diệt ma", "Làm nhiệm vụ hằng ngày phong phú nhiều phần quà : kinh nghiệm , trang bị , item .....", "Lệnh bài gia tốc cấp độ có thể kiếm được thông qua : train , nhiệm vụ hằng ngày , rương  và săn boss", "Nhiệm vụ chính tuyến kết thúc ở level 30", "Tối đa có thể làm 5 nhiệm vụ bang 1 ngày", "Tích cực tham gia nhiệm vụ bang để được nhiều phần quà hấp dẫn", "Giao dịch cá nhân nếu hơn 30s sẽ bị hủy", "Màu sắc trang bị từ thấp đến cao : trắng - xanh - vàng - tím - cam", "Tối đa số lần có thể vào Vượt ải đơn và nhóm là 5", "Mỗi ngày sẽ được miến phí 1 lần vào vượt ải một mình và 1 lần vượt ải nhóm", "Thời gian vượt ải một mình là 30p và nhóm là 45p", "Số ải ở vượt ải đơn là 20 và 1 ải đặc biệt khi qua hết 20 ải", "Số ải ở vượt ải nhóm là 25 và 1 ải đặc biệt khi qua hết 25 ải", "Thời gian tính từ khi rời bang và gia nhập bang khác là 12h"};
      infoClan = new String[]{"Tên", "Chức vụ", "Cống hiến", "Trạng thái"};
      tClan = new String[]{"Thông tin", "Thành viên", "Chức năng"};
      serverName = new String[]{"Máy Chủ Kim Long", "Máy Chủ Hỏa Long (new)"};
      listKhan = new String[]{"Tháo Cờ", "Đỏ", "Xanh Lá", "Xanh Dương", "Vàng", "Cam"};
      classintro = new String[][]{{"Được xem là Thái Sơn Bắc Đầu về thiền và võ học trong võ lâm, từ khi lập phái đến nay luôn lấy chủ trương chính nghĩa làm mục đích, do đó mà có uy danh rất lớn.", "Truyền bá giáo lý đạo gia, đặc điểm của Vô cực đạo là hình thần hợp nhất, chú trọng dưỡng khí không dùng lực làm sở trường, là môn phái có địa vị cao nhất nhì trong võ lâm.", "Tập hợp những người phẩm cách cao thượng, kiên cường, nghĩa khí ngút trời chuyên trừ bạo giúp yếu, trọng tín, là môn phái chính đạo nổi tiếng trên giang hồ."}, {"Là môn phái toàn nữ nhưng không thua kém mày râu, ghét ác như kẻ thù, hành hiệp trượng nghĩa. Nổi tiếng về kiếm pháp nhẹ nhàng nhưng cũng không kém phần uy lực. ", "Nổi tiếng về phát minh ám khí và thuốc độc, uy lực kinh người, là môn phái bí hiểm, hành vi thoắt ẩn thoắt hiện khó phân biệt chính tà. Thần bí là từ luôn được nhắc đến khi nói về Ma Chu Cốc."}};
      className = new String[]{"Trúc lâm tự", "Hoả long bang", "Thuỷ liên viện", "Vô cực đạo", "Ma chu cốc"};
      infoclass = new String[][]{{"Trúc Lâm Tự", "Vô Cực Đạo", "Hỏa Long Bang"}, {"Thủy Liên Viện", "Ma Chu Cốc"}};
      hungcanh = new String[]{"  HA HA HA!!! ", " Không biết tự lượng sức !", " Bọn ngươi còn yếu lắm hẹn gặp lại lần sau ", " Cút ! "};
      Texintro = new String[][]{{" Trúc Lâm tự thật phải có trách nhiệm lớn sự việc này", " Khi đã tạo ra tên phản đồ Hùng Cảnh khi sư diệt tổ"}, {" Lão Hùng Cảnh muốn xưng bá võ lâm.", " Lập ra môn phái riêng.", " Liên tục tạo ra mâu thuẩn hiểu lầm cho võ lâm đồng đạo.", " Điều này là không thể chấp nhận", " Các võ lâm đồng đạo có nhất trí tìm hắn làm rõ sự việc này không ?"}, {" Chuyện này không phải chuyện riêng của Trúc Lâm Tự nữa rồi.", " Cái ghế võ lâm minh chủ phải dành cho người xứng đáng ngồi"}, {" Nghe đồn lão nghịch luyện Dịch Cân Kinh không thành Phật mà đã nhập Ma đạo.", " Chuyến đi này mọi người nên cẩn thận"}, {" Để coi Ma đạo mạnh hay Ma Chu Cốc ta mạnh ?"}};
      talkwhenfight = new String[][]{{" phản đồ !"}, {" người còn cười được ?"}, {" sao phải nhiều lời. LÊN."}, {" ghế minh chủ võ lâm không phải dành cho ngươi."}, {" Xông lên "}};
      namelistQuest = new String[]{"Nhiệm Vụ Chính", "Nhiệm Vụ Phụ", "Hoàn Thành"};
      Sudung = "Sử dụng";
      Vut = "Vứt";
      Ban = "Bán";
      menuAuto = new String[][]{{"Bật tự động đánh", "Tự dùng HP", "Tự dùng MP"}, {"Không nhặt HP/MP", "Chỉ nhặt đồ màu", "Không nhặt nguyên liệu"}, {"", "", ""}};
      tfocus = new String[]{"Xem thông tin", "Kết bạn", "Nhắn tin", "Mời vào nhóm", "Thách đấu"};
      nameTabAuto = new String[]{"Đánh", "Nhặt", "Hỗ trợ", "Cài Đặt"};
      type = "Loại";
      typeSkill = new String[]{"Tấn công", "Hỗ trợ", "Bị động"};
      Thoigianhotro = "Thời gian hỗ trợ";
      Thoigianhoi = "Thời gian hồi";
      infoTiemNang = new String[]{"Sức mạnh \n Cộng điểm vào sức mạnh sẽ tăng sát thương", "Thân pháp \n Cộng điểm vào thân pháp sẽ tăng chính xác và né tránh", "Linh khí \n Cộng điểm vào linh khí sẽ tăng nội lực (mp)", "Sinh khí \n Cộng điểm vào sinh khí sẽ tăng máu (hp)"};
      nametiemnang = new String[]{"Sức mạnh", "Thân pháp", "Linh khí", "Sinh khí"};
      LvYeuCau = "Level yêu cầu";
      Tieuhaonoiluc = "Tiêu hao nội lực";
      Tabmuctieu = new String[]{"Nhạc Hiệu Ứng", "Nhạc Nền", "Hiệu Ứng", "Ẩn người chơi"};
      Banbe = "Bạn bè";
      Tuyetgiao = "Tuyệt giao";
      Xemthongtin = "Xem thông tin";
      chapnhan = "Chấp nhận";
      tuchoi = "Từ chối";
      yeucauketban = "Yêu cầu kết bạn";
      hoigiaodich = " muốn mời bạn giao dịch. Bạn có đồng ý không?";
      hoithachdau = " gởi cho bạn một lời mời thách đấu. Mức cược là ";
      huygiaodich = "Giao dịch của bạn đã bị hủy.";
      loimoiParty = " muốn mời bạn vào nhóm. Bạn có đồng ý không?";
      moivaoclan = " mời bạn vào Bang.";
      tabThuLinh = "Thủ lĩnh";
      tabBangHoi = "Bang Hội";
      cancel = "Hủy";
      info = "Thông tin";
      view = "Xem";
      delMess = "Xóa sự kiện";
      menu = "Menu";
      mevent = "Sự kiện";
      noEvent = "Danh sách rỗng";
      coin = "xu";
      loimoikb = "Yêu cầu kết bạn.";
      Toc_khac = "Tóc khác";
      hoatdong = "Hướng dẫn";
   }
}
